### ISSUE TITLE
Testing the mod on my home server with a custom mod pack.  Crashed when I tried to grow a sapling into a tree

### ISSUE THREAD

**Issue by grydian** [CombatZAK/foregoing-rubbertrees#1]
Here is the pastebin of the crash.  https://pastebin.com/k2r1axkg   I had explored new areas got some world gen and chopped down the trees.  saplings dropped like it should.  Went back and tried to setup a manual tree farm near my base and that crash happened shortly after I planted them.  Thanks for making this mod I love it!  :)

**Comment by CombatZAK** [comment]
Stacktraces makes it look like it might be a compat issue with another mod that overrides world gen - 

```
    at com.github.terminatornl.tickcentral.api.TickHub.trueRandomTick(TickHub.java:28)
    at com.github.terminatornl.tickcentral.api.TickInterceptor.redirectRandomTick(TickInterceptor.java:20)
```

If TickCentral hides a forge biome method that I'm using then there's not much I can do. This is the line that is throwing:

if (b.getBiomeName().toLowerCase(Locale.US).contains("mega"))

I suspect that TickCentral is hiding getBiomeName for some reason

**Comment by grydian** [comment]
Very interesting.  Any idea what mod could be doing that?  I really appreciate your help.

**Comment by grydian** [comment]
Never mind.  Its lag googles.  I never use the mod anyways.  Thanks!

**Comment by CombatZAK** [comment]
can you pastebin your debug.log in a world where this happens?
