### ISSUE TITLE
Sapling doesn't grow into tree

### ISSUE THREAD

**Issue by grydian** [CombatZAK/foregoing-rubbertrees#2]
I removed lag-googles and planted a sapling on my home server put some bone meal on it and the sapling just vanished.  Did not grow a tree.  I can test in single player if you like.

**Comment by CombatZAK** [comment]
try removing TerminatorNL - the core mod for lag-goggles.

**Comment by CombatZAK** [comment]
Sorry - TickCentral I think is the name of the mod

**Comment by grydian** [comment]
I removed both when I removed lag-goggles

**Comment by CombatZAK** [comment]
can you pastebin your debug.log in a world where this happens?

**Comment by grydian** [comment]
I had a huge log so I had to just to the most recent stuff.  To make sure its in the log I recreated the bug.  IE I tried to make another sapling grow.  I can see your stuff in the debug log.  Hope this helps.  https://pastebin.com/vq0MFtZW

**Comment by CombatZAK** [comment]
>>> getBiomeName is client-side only. This will fail on SMP; switch to registry lookup to fix.

Thanks for your report! I'll publish another release shortly. Sidenote: this was very likely not an issue with the other mod lag-goggles, which only manifested this bug as a different symptom. When you get the new version they should both work without issue.

**Comment by grydian** [comment]
Very cool thanks so much!  :)

**Comment by CombatZAK** [comment]
Mod is approved on curse; if you can, please verify with 1.0.3

**Comment by grydian** [comment]
Worked great!  Thanks a ton!  Was able to grow saplings into trees etc.  Awesome!

**Comment by MagmaSlime123** [comment]
> > > > getBiomeName is client-side only. This will fail on SMP; switch to registry lookup to fix.
> 
> Thanks for your report! I'll publish another release shortly. Sidenote: this was very likely not an issue with the other mod lag-goggles, which only manifested this bug as a different symptom. When you get the new version they should both work without issue.

You have 1 new issue.
